worker: worker-linux-12-1.bb.travis-ci.org:travis-linux-1
language: java
jdk:
  - openjdk7
  - openjdk6
  
  notifications:
  recipients:
    - bal.mukund4u@gmail.com
    - bmukund@nuodb.com
    
    
